### Linear Algebra. Matrix. Part 1

$$
A=[a_{ij}]
=
\left[
\begin{array}{cccc}
   a_{11} & a_{12} & \cdots & a_{1n} \\
   a_{21} & a_{22} & \cdots & a_{2n} \\
   \vdots & \vdots & \quad & \vdots \\
   a_{m1} & a_{m2} & \cdots & a_{mn}
\end{array}
\right]\\
$$
where:
$a_{ij} \in \mathbb{R},\\
n,m \in \mathbb{N},\\
i=1,...,n, \\
j=1,...,m
$

In [1]:
import numpy as np
a_4x3 = np.array([[5,6,6],[1,5,3],[8,2,4],[9,2,0]])
print(a_4x3)

[[5 6 6]
 [1 5 3]
 [8 2 4]
 [9 2 0]]


#### Identity matrix

$$
I_n=[a_{ij}]=
\left[
\begin{array}{cccccc}
   1 & 0 & \cdots & 0 & \cdots & 0\\
   0 & 1 & \cdots & 0 & \cdots & 0 \\
   \vdots & \vdots & \ddots & \vdots & \ddots & \vdots \\
   0 & 0 & \cdots & 1 & \cdots & 0 \\
   \vdots & \vdots & \ddots & \vdots & \ddots & \vdots \\
   0 & 0 & \cdots & 0 & \cdots & 1
\end{array}
\right]
$$
where:  
$
\in\mathbb{R}^{nxn}
$

$$
I_n=[a_{ij}]
$$  
where:  
$
a_{ij}=
\begin{cases} 
1, \quad if \quad i=j,\\
0, \quad if \quad i\neq j
\end{cases}
$

In [5]:
def create_identity_matrix(n: int):
    '''
    This function creates a n-by-n identity matrix
    
    INPUT: n:integer - nubmer of rows of an identity matrix
    number of rows will be equal to number of columns, since
    identity matrices are squares.
    
    OUTPUT: matrix:ndarray - an identity matrix of n rows
    and n columns.    
    '''
    matrix = list()
    for i in range(n):
        vect = list()
        for j in range(n):
            if i == j:
                vect.append(1)
            else:
                vect.append(0)
        matrix.append(vect)
    matrix = np.array(matrix)
    return matrix

In [6]:
print(create_identity_matrix(5))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


#### Matrix addition

$$
C=A+B
$$ 
where:  
$A, B, C \in\mathbb{R}^{mxn}
$

$$
c_{ij} = a_{ij}+b_{ij}
$$
where:  
$
i = 1,...,m,\\
j = 1,...,n
$

In [7]:
a = np.array([[2,3,5],[5,2,6],[5,6,3],[5,2,1]])
b = np.array([[6,4,1],[4,2,1],[0,8,4],[3,1,1]])
print('Matrix A')
print(a)
print('---------')
print('Matrix B')
print(b)

Matrix A
[[2 3 5]
 [5 2 6]
 [5 6 3]
 [5 2 1]]
---------
Matrix B
[[6 4 1]
 [4 2 1]
 [0 8 4]
 [3 1 1]]


In [8]:
def add_matrices(a, b):
    '''
    This function checks if the two matrices have the same shape
    and if they do, it preforms addition
    
    INPUT: 
        a:ndarray - matrix A
        b:ndarray - matrix B
    OUTPUT:
        c:ndarray - result of multiplication of matrices A and B
    '''
    if a.shape == b.shape:
        c = a+b
        return c
    else:
        return print('Please check the shape of the matrices.\
        They should be equal')

In [11]:
print(add_matrices(a, b))

[[ 8  7  6]
 [ 9  4  7]
 [ 5 14  7]
 [ 8  3  2]]


#### Multiplication with a Scalar

$$
B = \lambda A
$$
where:  
$
A, B \in \mathbb{R}^{mxn},\\
\lambda \in \mathbb{R}
$
<br/>
$$
b_{ij}=\lambda a_{ij}
$$
where:  
$
i = 1,...,m,\\
j = 1,...,n
$

In [13]:
a = np.array([[2,3,5],[5,2,6],[5,6,3],[5,2,1]])
scalar = 2
print('Matrix A')
print(a)
print('---------')
print('Scalar')
print(scalar)

Matrix A
[[2 3 5]
 [5 2 6]
 [5 6 3]
 [5 2 1]]
---------
Scalar
2


In [14]:
def mult_scalar(matrix, scalar:float):
    '''
    This function multiplies matrix with a scalar
    
    INPUT:
        matrix:np.array - matrix to be multiplied
        scalar:float - a scalar to be multiplied
    OUTPUT:
        b:np.array - resulting matrix   
    '''
    b = matrix * scalar
    return b

In [16]:
print(mult_scalar(a, scalar))

[[ 4  6 10]
 [10  4 12]
 [10 12  6]
 [10  4  2]]


### Division by a scalar

$$
B = \frac{A}{\lambda}
$$
where:  
$ 
A, B \in \mathbb{R}^{mxn},\\
\lambda \in \mathbb{R} \neq0
$
<br/>
$$
b_{ij}= \frac{a_{ij}}{\lambda}
$$
where:  
$
i = 1,...,m,\\
j = 1,...,n
$

In [17]:
def div_scalar(matrix, scalar:float):
    '''
    This function multiplies matrix with a scalar

    INPUT:
        matrix:np.array - matrix to be divided
        scalar:float - a scalar should not be equal to zero
    OUTPUT:
        b:np.array - resulting matrix   
    '''
    b = matrix / scalar
    return b

In [18]:
print(div_scalar(a, scalar))

[[1.  1.5 2.5]
 [2.5 1.  3. ]
 [2.5 3.  1.5]
 [2.5 1.  0.5]]


$$
C=AB$$ 
where:
$A\in \mathbb{R}^{mxn}\\ 
B \in \mathbb{R}^{nxk}\\
C\in\mathbb{R}^{mxk}
$


$$
c_{ij}=\sum \limits _{l=1} ^{n} a_{il}b_{lj}
$$
where:  
$i=1,...,m,\\
j=1,...,k
$

In [69]:
mat_4x3 = np.array([[4,2,3],[5,8,2],[1,0,1],[7,2,1]])
mat_3x2 = np.array([[5,2],[0,1],[3,2]])
print('Matrix A 4x3')
print(mat_4x3)
print('------------')
print('Matrix B 3x2')
print(mat_3x2)

Matrix A 4x3
[[4 2 3]
 [5 8 2]
 [1 0 1]
 [7 2 1]]
------------
Matrix B 3x2
[[5 2]
 [0 1]
 [3 2]]


$
c_{11}=\sum \limits _{l=1} ^{3} a_{1l}b_{l1}
$

In [36]:
c_11 = (mat_4x3[0,:] * mat_3x2[:,0]).sum()
print(c_11)

29


$
c_{12}=\sum \limits _{l=1} ^{3} a_{1l}b_{l2}
$

In [44]:
c_12 = (mat_4x3[0,:] * mat_3x2[:,1]).sum()
print(c_12)

16


$
c_{21}=\sum \limits _{l=1} ^{3} a_{2l}b_{l1}
$

In [38]:
c_21 = (mat_4x3[1,:] * mat_3x2[:,0]).sum()
print(c_21)

31


$
c_{22}=\sum \limits _{l=1} ^{3} a_{2l}b_{l2}
$

In [39]:
c_22 = (mat_4x3[1,:] * mat_3x2[:,1]).sum()
print(c_22)

22


$
c_{31}=\sum \limits _{l=1} ^{3} a_{3l}b_{l1}
$

In [40]:
c_31 = (mat_4x3[2,:] * mat_3x2[:,0]).sum()
print(c_31)

8


$
c_{32}=\sum \limits _{l=1} ^{3} a_{3l}b_{l2}
$

In [41]:
c_32 = (mat_4x3[2,:] * mat_3x2[:,1]).sum()
print(c_32)

4


$
c_{41}=\sum \limits _{l=1} ^{3} a_{4l}b_{l1}
$

In [42]:
c_41 = (mat_4x3[3,:] * mat_3x2[:,0]).sum()
print(c_41)

38


$
c_{42}=\sum \limits _{l=1} ^{3} a_{4l}b_{l2}
$

In [43]:
c_42 = (mat_4x3[3,:] * mat_3x2[:,1]).sum()
print(c_42)

18


In [46]:
matrix_c4x2 = np.array([[c_11, c_12], [c_21, c_22], [c_31, c_32], [c_41, c_42]])
print(matrix_c4x2)

[[29 16]
 [31 22]
 [ 8  4]
 [38 18]]


In [51]:
a = mat_4x3
b = mat_3x2

In [52]:
a

array([[4, 2, 3],
       [5, 8, 2],
       [1, 0, 1],
       [7, 2, 1]])

In [70]:
def mat_mult(mat_a, mat_b):
    '''
    This function multiplies two matrices
    
    INPUT:
        mat_a:ndarray - matrix with mxn dimensions
        mat_b:ndarray - matrix with nxk dimensions
    OUTPUT:
        mat_c:ndarray - matrix with mxk dimensions
    '''
    if mat_a.shape[1] == mat_b.shape[0]:
        cols = list()
        for i in range(len(a)):
            rows = list()
            a_il = a[i,:]
            for j in range(len(b[0])):
                b_lj = b[:,j]
                c_ij = (a_il * b_lj).sum()
                rows.append(c_ij)
            cols.append(rows)
        mat_c = np.array(cols)
        return mat_c
    else:
        return print('Make sure that neighboring dimensions are the same for both matrices')

In [74]:
mat_4x2 = mat_mult(mat_4x3, mat_3x2)
print('Matrix A')
print(mat_4x3)
print('----------')
print('Matrix B')
print(mat_3x2)
print('----------')
print('Resulting Matrix C')
print(mat_4x2)

Matrix A
[[4 2 3]
 [5 8 2]
 [1 0 1]
 [7 2 1]]
----------
Matrix B
[[5 2]
 [0 1]
 [3 2]]
----------
Resulting Matrix C
[[29 16]
 [31 22]
 [ 8  4]
 [38 18]]


In [77]:
mat_4x2 = np.dot(mat_4x3, mat_3x2)
print(mat_4x2)

[[29 16]
 [31 22]
 [ 8  4]
 [38 18]]


### Transpose

$$
B = A^T
$$
where  
$A\in \mathbb{R}^{mxn},\\
B\in\mathbb{R}^{nxm},\\
b_{ij}=a_{ji},\\
n,m \in \mathbb{N}$

In [81]:
# Define a 4x5 matrix
mat_4x5 = np.array([[4,2,6,4,2], [7,2,6,4,5], [6,2,3,2,1],[1,0,2,6,8]])
print('Matrix A')
print(mat_4x5)
print('---------')
print('Martix B(A transposed)')
print(mat_4x5.T)

Matrix A
[[4 2 6 4 2]
 [7 2 6 4 5]
 [6 2 3 2 1]
 [1 0 2 6 8]]
---------
Martix B(A transposed)
[[4 7 6 1]
 [2 2 2 0]
 [6 6 3 2]
 [4 4 2 6]
 [2 5 1 8]]
